-- MySQL Script generated by MySQL Workbench
-- Fri Jul 12 23:33:06 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema masgas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema masgas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `masgas` DEFAULT CHARACTER SET utf8 ;
USE `masgas` ;

-- -----------------------------------------------------
-- Table `masgas`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `masgas`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `masgas`.`Usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `activo` TINYINT(1) NULL DEFAULT 1,
  `tipoUsuario` ENUM("cliente", "empresa", "admin") NOT NULL,
  `creado` DATETIME NULL,
  `modificado` DATETIME NULL,
  `telefono` VARCHAR(20) NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idUsuarios_UNIQUE` (`idUsuario` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `masgas`.`Empresas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `masgas`.`Empresas` ;

CREATE TABLE IF NOT EXISTS `masgas`.`Empresas` (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(100) NULL,
  `telefono` VARCHAR(20) NULL,
  `identificadorFiscal` VARCHAR(20) NULL,
  `logotipo` VARCHAR(45) NULL,
  `titular` INT NOT NULL,
  PRIMARY KEY (`idEmpresa`),
  UNIQUE INDEX `idEmpresa_UNIQUE` (`idEmpresa` ASC) VISIBLE,
  UNIQUE INDEX `identidadFiscal_UNIQUE` (`identificadorFiscal` ASC) VISIBLE,
  INDEX `usuario_idx` (`titular` ASC) VISIBLE,
  CONSTRAINT `usuarioE`
    FOREIGN KEY (`titular`)
    REFERENCES `masgas`.`Usuarios` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `masgas`.`Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `masgas`.`Productos` ;

CREATE TABLE IF NOT EXISTS `masgas`.`Productos` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `tipoGas` ENUM("Normal", "Premium") NOT NULL,
  `tipoEnvase` ENUM("3kg", "5kg", "10kg", "15kg", "45kg") NOT NULL,
  `diametro_mm` INT NOT NULL,
  `altura_mm` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProducto`),
  UNIQUE INDEX `idProducto_UNIQUE` (`idProducto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `masgas`.`Compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `masgas`.`Compras` ;

CREATE TABLE IF NOT EXISTS `masgas`.`Compras` (
  `idCompras` INT NOT NULL AUTO_INCREMENT,
  `comprador` INT NOT NULL,
  `direccionEnvio` VARCHAR(100) NULL,
  `estadoCompra` ENUM("Pendiente", "En curso", "Entregada") NULL,
  `formaPago` ENUM("Efectivo", "Transferencia", "Tarjeta") NULL,
  `fechaCompra` DATETIME NULL,
  PRIMARY KEY (`idCompras`),
  UNIQUE INDEX `idCompras_UNIQUE` (`idCompras` ASC) VISIBLE,
  INDEX `comprador_idx` (`comprador` ASC) VISIBLE,
  CONSTRAINT `comprador`
    FOREIGN KEY (`comprador`)
    REFERENCES `masgas`.`Usuarios` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `masgas`.`Productos-Empresas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `masgas`.`Productos-Empresas` ;

CREATE TABLE IF NOT EXISTS `masgas`.`Productos-Empresas` (
  `idProductos-Empresas` INT NOT NULL AUTO_INCREMENT,
  `producto` INT NOT NULL,
  `empresa` INT NOT NULL,
  `precio` DECIMAL(2) NOT NULL,
  `disponibles` INT NULL,
  `imagen` VARCHAR(45) NULL,
  PRIMARY KEY (`idProductos-Empresas`),
  UNIQUE INDEX `idProductos-Empresas_UNIQUE` (`idProductos-Empresas` ASC) VISIBLE,
  INDEX `producto_idx` (`producto` ASC) VISIBLE,
  INDEX `empresa_idx` (`empresa` ASC) VISIBLE,
  CONSTRAINT `productoPE`
    FOREIGN KEY (`producto`)
    REFERENCES `masgas`.`Productos` (`idProducto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `empresaPE`
    FOREIGN KEY (`empresa`)
    REFERENCES `masgas`.`Empresas` (`idEmpresa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `masgas`.`Productos-Compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `masgas`.`Productos-Compra` ;

CREATE TABLE IF NOT EXISTS `masgas`.`Productos-Compra` (
  `idProductos-Compra` INT NOT NULL AUTO_INCREMENT,
  `compra` INT NOT NULL,
  `producto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`idProductos-Compra`),
  UNIQUE INDEX `idProductos-Compra_UNIQUE` (`idProductos-Compra` ASC) VISIBLE,
  INDEX `compra_idx` (`compra` ASC) VISIBLE,
  INDEX `producto_idx` (`producto` ASC) VISIBLE,
  CONSTRAINT `compraPC`
    FOREIGN KEY (`compra`)
    REFERENCES `masgas`.`Compras` (`idCompras`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `productoPC`
    FOREIGN KEY (`producto`)
    REFERENCES `masgas`.`Productos-Empresas` (`idProductos-Empresas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `masgas`.`Opiniones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `masgas`.`Opiniones` ;

CREATE TABLE IF NOT EXISTS `masgas`.`Opiniones` (
  `idOpiniones` INT NOT NULL AUTO_INCREMENT,
  `usuario` INT NOT NULL,
  `empresa` INT NOT NULL,
  `puntuacion` INT NOT NULL,
  `comentario` VARCHAR(200) NULL,
  `fecha` DATETIME NOT NULL,
  `compra` INT NOT NULL,
  PRIMARY KEY (`idOpiniones`),
  UNIQUE INDEX `idOpiniones_UNIQUE` (`idOpiniones` ASC) VISIBLE,
  INDEX `usuario_idx` (`usuario` ASC) VISIBLE,
  INDEX `empresa_idx` (`empresa` ASC) VISIBLE,
  INDEX `compra_idx` (`compra` ASC) VISIBLE,
  CONSTRAINT `usuarioO`
    FOREIGN KEY (`usuario`)
    REFERENCES `masgas`.`Usuarios` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `empresaO`
    FOREIGN KEY (`empresa`)
    REFERENCES `masgas`.`Empresas` (`idEmpresa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `compraO`
    FOREIGN KEY (`compra`)
    REFERENCES `masgas`.`Compras` (`idCompras`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
